# yamllint disable
name: Build documentation

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4c-multiphysics/4c-minimal:main
      options: --user root --env OMPI_ALLOW_RUN_AS_ROOT=1 --env OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.67.0
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: queens-dev
          frozen: true
          activate-environment: queens-dev
      - name: Install QUEENS in workspace
        run: |
          pixi run --locked -e queens-dev python -m pip install --no-deps -e .
      - name: Mark repo as safe for git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync
      - name: Create links to 4C
        run: |
          ln -s /home/user/4C/bin/ config/4C_build
      - name: Register Jupyter kernel
        run: |
          python -m ipykernel install --user --name queens --display-name "Python (queens)"
      - name: Install xvfb
        run: |
          apt-get update
          apt-get install -y xvfb
      - name: Sphinx build
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          set -euxo pipefail
          sphinx-apidoc -o doc/source src/ -fMT
          cd doc
          xvfb-run -a sphinx-build -b html -d build/doctrees source build/html -W
      - name: Upload html
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/build/html
          retention-days: 1

  deploy-documentation:
    name: Deploy documentation
    needs: build-documentation
    if: ${{github.ref == 'refs/heads/main'}}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
